Feat/lambda@edge
polestar/nextjs-cdk pull request #31
Opened 2021-11-17 12:59 UTC by JoelRoxell

* adds lambda edge support
* adds a common construct (NextJSConstruct) to share deployment structures between different strategies 
* consolidates lambda-handler names

2021-11-17 13:03 UTC, JoelRoxell commented on src/cdk/strategies/NextJSAPIGateway.ts
> +export class NextJSAPIGateway extends cdk.Construct {
This strategy should make use of shared functions from NextJSConstruct (however, in another PR)

2021-11-17 13:03 UTC, JoelRoxell commented on src/handlers/core/handle/default.ts
> +    console.log('isRender');
rm

2021-11-17 13:03 UTC, JoelRoxell commented on src/handlers/core/handle/default.ts
> +    console.log('is api route');
rm

2021-11-18 11:22 UTC, andersquist requested changes
Looks good a part from some minor stuff! 👍

Would be great if the e2e test could be added to the `e2e-test.yml` workflow.

2021-11-18 11:22 UTC, andersquist commented on src/cdk/index.ts
> -}
It would have been nice to have this move tracked as a move by git because now we lose all the history...

2021-11-18 11:22 UTC, andersquist commented on src/common/LambdaHandlerTypes.ts
> +}
Not sure about this. I get the idea but it isn't really a type in this case but rather a `const` right? Or maybe a descriminator perhaps with the necessary changes.

2021-11-18 11:22 UTC, andersquist commented on src/build/LambdaEdgeBuilder.ts
> +    );
I think this a bit unclear. Do we need to build the default handler for (API GW?) when building for the edge?

Wont it have the wrong request/response signatures?

2021-11-18 11:22 UTC, andersquist commented on src/build/LambdaEdgeBuilder.ts
> +export class LambdaEdgeBuilder extends LambdaBuilder {
Is it necessary to subclass the LambdaBuilder when all we do is override and add one change as far as I can see?

2021-11-18 11:22 UTC, andersquist commented on src/build/lambda-builder.ts
> +    handler: LambdaHandlerTypes,
Why not `handlerType`. Just `handler` would indicate that it could be the actual handler that we're using. And as I mentioned above I think it is a bit unclear what a type is when it is also a path `const`.

2021-11-18 11:22 UTC, andersquist commented on src/cdk/strategies/NextJSAPIGateway.ts
> +export class NextJSAPIGateway extends cdk.Construct {
Yes, that would be a good idea! 👍

2021-11-18 11:22 UTC, andersquist commented on tests/e2e/next-app-edge/cypress/support/commands.ts
> +// ***********************************************
I think shouldn't be duplicated but rather moved to a parent folder so that it could be used by all existing and future end to end tests.

2021-11-18 11:22 UTC, andersquist commented on tests/e2e/next-app-edge/tests/requests/default.json
> +{
This can't reallly be the same? The payload for a lambda@edge is not the same as for a Lambda Proxy.

2021-11-18 12:05 UTC, JoelRoxell commented on src/cdk/index.ts
> -}
I'll try to adjust it.

2021-11-18 12:06 UTC, JoelRoxell commented on src/common/LambdaHandlerTypes.ts
> +}
Is it just the naming that you're concerned with?

2021-11-18 12:07 UTC, JoelRoxell commented on src/build/LambdaEdgeBuilder.ts
> +    );
I currently left it in to use it since the handler supports the SQS event, didn't want to duplicate that code.

2021-11-18 12:07 UTC, JoelRoxell commented on src/build/LambdaEdgeBuilder.ts
> +    );
https://github.com/polestar/nextjs-cdk/blob/feat/lambda%40edge/src/handlers/lambda/default-handler.ts#L124

2021-11-18 13:32 UTC, andersquist commented on src/common/LambdaHandlerTypes.ts
> +}
I guess so and that it serves as both an `enum` and as a (magic) path `const`. Maybe not a biggy I guess.

2021-11-19 07:55 UTC, andersquist approved these changes

2021-11-19 13:10 UTC, merged