Feat/namespace
polestar/nextjs-cdk pull request #38
Opened 2021-11-25 18:19 UTC by JoelRoxell

adds namespace support for gw and edge

2021-11-26 08:18 UTC, JoelRoxell commented on src/cdk/strategies/NextJSConstruct.ts
> +      ).config.assetPrefix.replace('/', '') + '/'
rm post /, unclear intent.

2021-11-26 08:18 UTC, JoelRoxell commented on src/common/logger.ts
> +class Logger {
Always prints atm, log suppression based on NODE_ENV will be implemented later.

2021-11-26 08:18 UTC, JoelRoxell commented on src/handlers/core/route/index.ts
> +      `\\w/${SettingsFileReader.getAppNamespace()}/api`,
/market/namespace/api

2021-11-26 08:52 UTC, TastefulElk commented on src/common/logger.ts
> +    const body = JSON.stringify(data) || '';
Only stringify if data is object? Otherwise string will get double quoted

2021-11-26 09:52 UTC, andersquist requested changes

2021-11-26 09:52 UTC, andersquist commented on src/build/core-builder.ts
> +      'required-server-files.json',
Can't we just extend `manifest.json` with a new field, like `appNamespace` or something and populated that at build time instead of adding a whole new json file to the Lambdas?

2021-11-26 10:39 UTC, JoelRoxell commented on tests/e2e/next-app/pages/errored-page-new-ssr.tsx
> +export function getServerSideProps(
Well the project wouldn't build due to typescript interface violations

2021-11-26 10:40 UTC, JoelRoxell commented on tests/e2e/next-app/package.json
> +    "node-color-log": "^7.0.0",
sure

2021-11-26 10:41 UTC, JoelRoxell commented on src/build/core-builder.ts
> +      'required-server-files.json',
Added the entire file if we want to expose other settings that should be provided to the lambda.

2021-11-26 10:51 UTC, JoelRoxell commented on src/common/SettingsFileReader.ts
> +export class SettingsFileReader {
No sure if it's always generated by nextjs, so in this case, it makes use of it if it exists.

2021-11-26 10:58 UTC, JoelRoxell commented on src/build/core-builder.ts
> +      'required-server-files.json',
But sure, could make an effort to streamline it via manifes.

2021-11-26 11:05 UTC, andersquist commented on src/build/core-builder.ts
> +      'required-server-files.json',
It feels like this file is of a proprietary nature and as we already have the manifest it feels nice to have it there and typed as well.

2021-11-29 07:41 UTC, andersquist approved these changes

2021-11-29 11:21 UTC, merged